version: '3.2'
services:
  elastic_search:
    restart: 'always'
    ports:
    - '9200:9200'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch-container
    environment:
    - 'discovery.type=single-node'
    networks:
      infranet:
        aliases:
        - 'elasticsearch-service'
  es_exporter:
    restart: 'always'
    ports:
    - '9108:9108'
    image: justwatch/elasticsearch_exporter
    container_name: es-exporter-container
    command:
    - --es.uri=http://elasticsearch-service:9200
    depends_on:
    - elastic_search
    networks:
      infranet:
        aliases:
        - elasticsearch-exporter-service
  grafana:
    restart: 'always'
    ports:
    - '3000:3000'
    image: grafana/grafana
    container_name: grafana-container
  prometheus:
    restart: 'always'
    ports:
    - '9090:9090'
    image: prom/prometheus
    container_name: prometheus-container
    command:
    - '--config.file=/prometheus/config/prometheus.yaml'
    - '--storage.tsdb.path=/data'
    volumes:
    - ./config:/prometheus/config
    - ./data:/data
    depends_on:
    - es_exporter
    networks:
      infranet:
        aliases:
        - 'prometheus-service'
networks:
  infranet:
